# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

- job: BuildAndTest
  steps:
    - task: UseDotNet@2
      displayName: 'Setup .NET'
      inputs:
        packageType: 'sdk'
        version: '7.x'
    
    - script: echo "Some build or test steps"
      displayName: 'Build and test'

    # Original Post Setup step
    - script: echo "Post setup steps"
      displayName: 'Post Setup .NET'
      condition: always()  # This forces the step to run even if the previous steps fail
